version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: task-list/task-list
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres
      DB_USER: postgres
      DB_PASSWORD: postgres

  frontend:
    image: nginx:1.17.8
    volumes:
      - ./src/main/frontend:/code
    ports:
      - "9090:9090"
volumes:
  db:
    driver: local
