/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PageableObject,
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
} from './PageableObject';
import {
    Sort,
    SortFromJSON,
    SortFromJSONTyped,
    SortToJSON,
} from './Sort';
import {
    Task,
    TaskFromJSON,
    TaskFromJSONTyped,
    TaskToJSON,
} from './Task';

/**
 * 
 * @export
 * @interface PageTask
 */
export interface PageTask {
    /**
     * 
     * @type {number}
     * @memberof PageTask
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageTask
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageTask
     */
    number?: number;
    /**
     * 
     * @type {number}
     * @memberof PageTask
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageTask
     */
    numberOfElements?: number;
    /**
     * 
     * @type {Array<Task>}
     * @memberof PageTask
     */
    content?: Array<Task>;
    /**
     * 
     * @type {Sort}
     * @memberof PageTask
     */
    sort?: Sort;
    /**
     * 
     * @type {boolean}
     * @memberof PageTask
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageTask
     */
    last?: boolean;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageTask
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageTask
     */
    empty?: boolean;
}

export function PageTaskFromJSON(json: any): PageTask {
    return PageTaskFromJSONTyped(json, false);
}

export function PageTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageTask {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalPages': !exists(json, 'totalPages') ? undefined : json['totalPages'],
        'totalElements': !exists(json, 'totalElements') ? undefined : json['totalElements'],
        'number': !exists(json, 'number') ? undefined : json['number'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'numberOfElements': !exists(json, 'numberOfElements') ? undefined : json['numberOfElements'],
        'content': !exists(json, 'content') ? undefined : ((json['content'] as Array<any>).map(TaskFromJSON)),
        'sort': !exists(json, 'sort') ? undefined : SortFromJSON(json['sort']),
        'first': !exists(json, 'first') ? undefined : json['first'],
        'last': !exists(json, 'last') ? undefined : json['last'],
        'pageable': !exists(json, 'pageable') ? undefined : PageableObjectFromJSON(json['pageable']),
        'empty': !exists(json, 'empty') ? undefined : json['empty'],
    };
}

export function PageTaskToJSON(value?: PageTask | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalPages': value.totalPages,
        'totalElements': value.totalElements,
        'number': value.number,
        'size': value.size,
        'numberOfElements': value.numberOfElements,
        'content': value.content === undefined ? undefined : ((value.content as Array<any>).map(TaskToJSON)),
        'sort': SortToJSON(value.sort),
        'first': value.first,
        'last': value.last,
        'pageable': PageableObjectToJSON(value.pageable),
        'empty': value.empty,
    };
}

