/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskSo
 */
export interface TaskSo {
    /**
     * 
     * @type {string}
     * @memberof TaskSo
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskSo
     */
    description?: string;
}

export function TaskSoFromJSON(json: any): TaskSo {
    return TaskSoFromJSONTyped(json, false);
}

export function TaskSoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskSo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function TaskSoToJSON(value?: TaskSo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
    };
}

